[tool.poetry]
name = "py_assn_1"
version = "0.1.0"
description = "This package includes functions to print successful creation of pythonpackage"
authors = ["Aditya Bhatraju"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
Sphinx = "^3.5.1"
sphinxcontrib-napoleon = "^0.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"